language: php

php:
  - 7.3
  - 7.4
  - 8.0.0

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d rabbitmq
  - travis_retry composer self-update
  - travis_retry composer update --no-progress --no-interaction --prefer-dist
  - sleep 10

script:
  - composer test
